# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.velero.v1 import Backup as _Resource0
    from cloudcoil.models.velero.v1 import BackupRepository as _Resource1
    from cloudcoil.models.velero.v1 import BackupStorageLocation as _Resource2
    from cloudcoil.models.velero.v1 import DeleteBackupRequest as _Resource5
    from cloudcoil.models.velero.v1 import DownloadRequest as _Resource6
    from cloudcoil.models.velero.v1 import PodVolumeBackup as _Resource7
    from cloudcoil.models.velero.v1 import PodVolumeRestore as _Resource8
    from cloudcoil.models.velero.v1 import Restore as _Resource9
    from cloudcoil.models.velero.v1 import Schedule as _Resource10
    from cloudcoil.models.velero.v1 import ServerStatusRequest as _Resource11
    from cloudcoil.models.velero.v1 import VolumeSnapshotLocation as _Resource12
    from cloudcoil.models.velero.v2alpha1 import DataDownload as _Resource3
    from cloudcoil.models.velero.v2alpha1 import DataUpload as _Resource4

_MODELS = {
    ("Backup", "velero.io/v1"): ("cloudcoil.models.velero.v1", "Backup"),
    ("Backup", ""): ("cloudcoil.models.velero.v1", "Backup"),
    ("BackupRepository", "velero.io/v1"): ("cloudcoil.models.velero.v1", "BackupRepository"),
    ("BackupRepository", ""): ("cloudcoil.models.velero.v1", "BackupRepository"),
    ("BackupStorageLocation", "velero.io/v1"): (
        "cloudcoil.models.velero.v1",
        "BackupStorageLocation",
    ),
    ("BackupStorageLocation", ""): ("cloudcoil.models.velero.v1", "BackupStorageLocation"),
    ("DataDownload", "velero.io/v2alpha1"): ("cloudcoil.models.velero.v2alpha1", "DataDownload"),
    ("DataDownload", ""): ("cloudcoil.models.velero.v2alpha1", "DataDownload"),
    ("DataUpload", "velero.io/v2alpha1"): ("cloudcoil.models.velero.v2alpha1", "DataUpload"),
    ("DataUpload", ""): ("cloudcoil.models.velero.v2alpha1", "DataUpload"),
    ("DeleteBackupRequest", "velero.io/v1"): ("cloudcoil.models.velero.v1", "DeleteBackupRequest"),
    ("DeleteBackupRequest", ""): ("cloudcoil.models.velero.v1", "DeleteBackupRequest"),
    ("DownloadRequest", "velero.io/v1"): ("cloudcoil.models.velero.v1", "DownloadRequest"),
    ("DownloadRequest", ""): ("cloudcoil.models.velero.v1", "DownloadRequest"),
    ("PodVolumeBackup", "velero.io/v1"): ("cloudcoil.models.velero.v1", "PodVolumeBackup"),
    ("PodVolumeBackup", ""): ("cloudcoil.models.velero.v1", "PodVolumeBackup"),
    ("PodVolumeRestore", "velero.io/v1"): ("cloudcoil.models.velero.v1", "PodVolumeRestore"),
    ("PodVolumeRestore", ""): ("cloudcoil.models.velero.v1", "PodVolumeRestore"),
    ("Restore", "velero.io/v1"): ("cloudcoil.models.velero.v1", "Restore"),
    ("Restore", ""): ("cloudcoil.models.velero.v1", "Restore"),
    ("Schedule", "velero.io/v1"): ("cloudcoil.models.velero.v1", "Schedule"),
    ("Schedule", ""): ("cloudcoil.models.velero.v1", "Schedule"),
    ("ServerStatusRequest", "velero.io/v1"): ("cloudcoil.models.velero.v1", "ServerStatusRequest"),
    ("ServerStatusRequest", ""): ("cloudcoil.models.velero.v1", "ServerStatusRequest"),
    ("VolumeSnapshotLocation", "velero.io/v1"): (
        "cloudcoil.models.velero.v1",
        "VolumeSnapshotLocation",
    ),
    ("VolumeSnapshotLocation", ""): ("cloudcoil.models.velero.v1", "VolumeSnapshotLocation"),
}


@overload
def get_model(
    kind: Literal["Backup"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource0]: ...


@overload
def get_model(kind: Literal["Backup"], *, api_version: Literal[""] = "") -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["BackupRepository"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["BackupRepository"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["BackupStorageLocation"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["BackupStorageLocation"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["DataDownload"], *, api_version: Literal["velero.io/v2alpha1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["DataDownload"], *, api_version: Literal[""] = ""
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["DataUpload"], *, api_version: Literal["velero.io/v2alpha1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["DataUpload"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["DeleteBackupRequest"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["DeleteBackupRequest"], *, api_version: Literal[""] = ""
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["DownloadRequest"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["DownloadRequest"], *, api_version: Literal[""] = ""
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["PodVolumeBackup"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["PodVolumeBackup"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["PodVolumeRestore"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["PodVolumeRestore"], *, api_version: Literal[""] = ""
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["Restore"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource9]: ...


@overload
def get_model(kind: Literal["Restore"], *, api_version: Literal[""] = "") -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["Schedule"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource10]: ...


@overload
def get_model(kind: Literal["Schedule"], *, api_version: Literal[""] = "") -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["ServerStatusRequest"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["ServerStatusRequest"], *, api_version: Literal[""] = ""
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["VolumeSnapshotLocation"], *, api_version: Literal["velero.io/v1"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["VolumeSnapshotLocation"], *, api_version: Literal[""] = ""
) -> type[_Resource12]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
