# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import AwareDatetime, Field


class DataDownloadSpecTargetVolume(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataDownloadSpecTargetVolume"]:
            return DataDownloadSpecTargetVolume

        def build(self) -> "DataDownloadSpecTargetVolume":
            return DataDownloadSpecTargetVolume(**self._attrs)

        def namespace(self, value: str, /) -> Self:
            "Namespace is the target namespace"
            return self._set("namespace", value)

        def pv(self, value: str, /) -> Self:
            "PV is the name of the target PV that is created by Velero restore"
            return self._set("pv", value)

        def pvc(self, value: str, /) -> Self:
            "PVC is the name of the target PVC that is created by Velero restore"
            return self._set("pvc", value)

    class BuilderContext(BuilderContextBase["DataDownloadSpecTargetVolume.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataDownloadSpecTargetVolume.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataDownloadSpecTargetVolume."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["DataDownloadSpecTargetVolume", Builder]:
        return GenericListBuilder[
            DataDownloadSpecTargetVolume, DataDownloadSpecTargetVolume.Builder
        ]()

    namespace: str
    "Namespace is the target namespace"
    pv: str
    "PV is the name of the target PV that is created by Velero restore"
    pvc: str
    "PVC is the name of the target PVC that is created by Velero restore"


class DataDownloadStatusProgress(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataDownloadStatusProgress"]:
            return DataDownloadStatusProgress

        def build(self) -> "DataDownloadStatusProgress":
            return DataDownloadStatusProgress(**self._attrs)

        def bytes_done(self, value: int | None, /) -> Self:
            return self._set("bytes_done", value)

        def total_bytes(self, value: int | None, /) -> Self:
            return self._set("total_bytes", value)

    class BuilderContext(BuilderContextBase["DataDownloadStatusProgress.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataDownloadStatusProgress.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataDownloadStatusProgress."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataDownloadStatusProgress", Builder]:
        return GenericListBuilder[DataDownloadStatusProgress, DataDownloadStatusProgress.Builder]()

    bytes_done: Annotated[int | None, Field(alias="bytesDone")] = None
    total_bytes: Annotated[int | None, Field(alias="totalBytes")] = None


class DataUploadSpecCsiSnapshot(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataUploadSpecCsiSnapshot"]:
            return DataUploadSpecCsiSnapshot

        def build(self) -> "DataUploadSpecCsiSnapshot":
            return DataUploadSpecCsiSnapshot(**self._attrs)

        def snapshot_class(self, value: str | None, /) -> Self:
            "SnapshotClass is the name of the snapshot class that the volume snapshot is created with"
            return self._set("snapshot_class", value)

        def storage_class(self, value: str, /) -> Self:
            "StorageClass is the name of the storage class of the PVC that the volume snapshot is created from"
            return self._set("storage_class", value)

        def volume_snapshot(self, value: str, /) -> Self:
            "VolumeSnapshot is the name of the volume snapshot to be backed up"
            return self._set("volume_snapshot", value)

    class BuilderContext(BuilderContextBase["DataUploadSpecCsiSnapshot.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataUploadSpecCsiSnapshot.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataUploadSpecCsiSnapshot."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataUploadSpecCsiSnapshot", Builder]:
        return GenericListBuilder[DataUploadSpecCsiSnapshot, DataUploadSpecCsiSnapshot.Builder]()

    snapshot_class: Annotated[str | None, Field(alias="snapshotClass")] = None
    "SnapshotClass is the name of the snapshot class that the volume snapshot is created with"
    storage_class: Annotated[str, Field(alias="storageClass")]
    "StorageClass is the name of the storage class of the PVC that the volume snapshot is created from"
    volume_snapshot: Annotated[str, Field(alias="volumeSnapshot")]
    "VolumeSnapshot is the name of the volume snapshot to be backed up"


class DataUploadStatusProgress(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataUploadStatusProgress"]:
            return DataUploadStatusProgress

        def build(self) -> "DataUploadStatusProgress":
            return DataUploadStatusProgress(**self._attrs)

        def bytes_done(self, value: int | None, /) -> Self:
            return self._set("bytes_done", value)

        def total_bytes(self, value: int | None, /) -> Self:
            return self._set("total_bytes", value)

    class BuilderContext(BuilderContextBase["DataUploadStatusProgress.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataUploadStatusProgress.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataUploadStatusProgress."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataUploadStatusProgress", Builder]:
        return GenericListBuilder[DataUploadStatusProgress, DataUploadStatusProgress.Builder]()

    bytes_done: Annotated[int | None, Field(alias="bytesDone")] = None
    total_bytes: Annotated[int | None, Field(alias="totalBytes")] = None


class DataDownloadSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataDownloadSpec"]:
            return DataDownloadSpec

        def build(self) -> "DataDownloadSpec":
            return DataDownloadSpec(**self._attrs)

        def backup_storage_location(self, value: str, /) -> Self:
            "BackupStorageLocation is the name of the backup storage location\nwhere the backup repository is stored."
            return self._set("backup_storage_location", value)

        def cancel(self, value: bool | None, /) -> Self:
            "Cancel indicates request to cancel the ongoing DataDownload. It can be set\nwhen the DataDownload is in InProgress phase"
            return self._set("cancel", value)

        def data_mover_config(self, value: dict[str, str] | None, /) -> Self:
            "DataMoverConfig is for data-mover-specific configuration fields."
            return self._set("data_mover_config", value)

        def datamover(self, value: str | None, /) -> Self:
            'DataMover specifies the data mover to be used by the backup.\nIf DataMover is "" or "velero", the built-in data mover will be used.'
            return self._set("datamover", value)

        def operation_timeout(self, value: str, /) -> Self:
            "OperationTimeout specifies the time used to wait internal operations,\nbefore returning error as timeout."
            return self._set("operation_timeout", value)

        def snapshot_id(self, value: str, /) -> Self:
            "SnapshotID is the ID of the Velero backup snapshot to be restored from."
            return self._set("snapshot_id", value)

        def source_namespace(self, value: str, /) -> Self:
            "SourceNamespace is the original namespace where the volume is backed up from.\nIt may be different from SourcePVC\u0027s namespace if namespace is remapped during restore."
            return self._set("source_namespace", value)

        @overload
        def target_volume(
            self, value_or_callback: DataDownloadSpecTargetVolume, /
        ) -> "DataDownloadSpec.Builder": ...

        @overload
        def target_volume(
            self,
            value_or_callback: Callable[
                [DataDownloadSpecTargetVolume.Builder],
                DataDownloadSpecTargetVolume.Builder | DataDownloadSpecTargetVolume,
            ],
            /,
        ) -> "DataDownloadSpec.Builder": ...

        @overload
        def target_volume(
            self, value_or_callback: Never = ...
        ) -> "DataDownloadSpecTargetVolume.BuilderContext": ...

        def target_volume(self, value_or_callback=UNSET, /):
            "TargetVolume is the information of the target PVC and PV."
            if self._in_context and value_or_callback is UNSET:
                context = DataDownloadSpecTargetVolume.BuilderContext()
                context._parent_builder = self
                context._field_name = "target_volume"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataDownloadSpecTargetVolume.builder())
                if isinstance(output, DataDownloadSpecTargetVolume.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("target_volume", value)

    class BuilderContext(BuilderContextBase["DataDownloadSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataDownloadSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataDownloadSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataDownloadSpec", Builder]:
        return GenericListBuilder[DataDownloadSpec, DataDownloadSpec.Builder]()

    backup_storage_location: Annotated[str, Field(alias="backupStorageLocation")]
    "BackupStorageLocation is the name of the backup storage location\nwhere the backup repository is stored."
    cancel: bool | None = None
    "Cancel indicates request to cancel the ongoing DataDownload. It can be set\nwhen the DataDownload is in InProgress phase"
    data_mover_config: Annotated[dict[str, str] | None, Field(alias="dataMoverConfig")] = None
    "DataMoverConfig is for data-mover-specific configuration fields."
    datamover: str | None = None
    'DataMover specifies the data mover to be used by the backup.\nIf DataMover is "" or "velero", the built-in data mover will be used.'
    operation_timeout: Annotated[str, Field(alias="operationTimeout")]
    "OperationTimeout specifies the time used to wait internal operations,\nbefore returning error as timeout."
    snapshot_id: Annotated[str, Field(alias="snapshotID")]
    "SnapshotID is the ID of the Velero backup snapshot to be restored from."
    source_namespace: Annotated[str, Field(alias="sourceNamespace")]
    "SourceNamespace is the original namespace where the volume is backed up from.\nIt may be different from SourcePVC\u0027s namespace if namespace is remapped during restore."
    target_volume: Annotated[DataDownloadSpecTargetVolume, Field(alias="targetVolume")]
    "TargetVolume is the information of the target PVC and PV."


class DataDownloadStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataDownloadStatus"]:
            return DataDownloadStatus

        def build(self) -> "DataDownloadStatus":
            return DataDownloadStatus(**self._attrs)

        def completion_timestamp(self, value: AwareDatetime | None, /) -> Self:
            "CompletionTimestamp records the time a restore was completed.\nCompletion time is recorded even on failed restores.\nThe server\u0027s time is used for CompletionTimestamps"
            return self._set("completion_timestamp", value)

        def message(self, value: str | None, /) -> Self:
            "Message is a message about the DataDownload\u0027s status."
            return self._set("message", value)

        def node(self, value: str | None, /) -> Self:
            "Node is name of the node where the DataDownload is processed."
            return self._set("node", value)

        def phase(
            self,
            value: (
                Literal[
                    "New",
                    "Accepted",
                    "Prepared",
                    "InProgress",
                    "Canceling",
                    "Canceled",
                    "Completed",
                    "Failed",
                ]
                | None
            ),
            /,
        ) -> Self:
            "Phase is the current state of the DataDownload."
            return self._set("phase", value)

        @overload
        def progress(
            self, value_or_callback: DataDownloadStatusProgress | None, /
        ) -> "DataDownloadStatus.Builder": ...

        @overload
        def progress(
            self,
            value_or_callback: Callable[
                [DataDownloadStatusProgress.Builder],
                DataDownloadStatusProgress.Builder | DataDownloadStatusProgress,
            ],
            /,
        ) -> "DataDownloadStatus.Builder": ...

        @overload
        def progress(
            self, value_or_callback: Never = ...
        ) -> "DataDownloadStatusProgress.BuilderContext": ...

        def progress(self, value_or_callback=UNSET, /):
            "Progress holds the total number of bytes of the snapshot and the current\nnumber of restored bytes. This can be used to display progress information\nabout the restore operation."
            if self._in_context and value_or_callback is UNSET:
                context = DataDownloadStatusProgress.BuilderContext()
                context._parent_builder = self
                context._field_name = "progress"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataDownloadStatusProgress.builder())
                if isinstance(output, DataDownloadStatusProgress.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("progress", value)

        def start_timestamp(self, value: AwareDatetime | None, /) -> Self:
            "StartTimestamp records the time a restore was started.\nThe server\u0027s time is used for StartTimestamps"
            return self._set("start_timestamp", value)

    class BuilderContext(BuilderContextBase["DataDownloadStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataDownloadStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataDownloadStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataDownloadStatus", Builder]:
        return GenericListBuilder[DataDownloadStatus, DataDownloadStatus.Builder]()

    completion_timestamp: Annotated[AwareDatetime | None, Field(alias="completionTimestamp")] = None
    "CompletionTimestamp records the time a restore was completed.\nCompletion time is recorded even on failed restores.\nThe server\u0027s time is used for CompletionTimestamps"
    message: str | None = None
    "Message is a message about the DataDownload\u0027s status."
    node: str | None = None
    "Node is name of the node where the DataDownload is processed."
    phase: (
        Literal[
            "New",
            "Accepted",
            "Prepared",
            "InProgress",
            "Canceling",
            "Canceled",
            "Completed",
            "Failed",
        ]
        | None
    ) = None
    "Phase is the current state of the DataDownload."
    progress: DataDownloadStatusProgress | None = None
    "Progress holds the total number of bytes of the snapshot and the current\nnumber of restored bytes. This can be used to display progress information\nabout the restore operation."
    start_timestamp: Annotated[AwareDatetime | None, Field(alias="startTimestamp")] = None
    "StartTimestamp records the time a restore was started.\nThe server\u0027s time is used for StartTimestamps"


class DataUploadSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataUploadSpec"]:
            return DataUploadSpec

        def build(self) -> "DataUploadSpec":
            return DataUploadSpec(**self._attrs)

        def backup_storage_location(self, value: str, /) -> Self:
            "BackupStorageLocation is the name of the backup storage location\nwhere the backup repository is stored."
            return self._set("backup_storage_location", value)

        def cancel(self, value: bool | None, /) -> Self:
            "Cancel indicates request to cancel the ongoing DataUpload. It can be set\nwhen the DataUpload is in InProgress phase"
            return self._set("cancel", value)

        @overload
        def csi_snapshot(
            self, value_or_callback: DataUploadSpecCsiSnapshot | None, /
        ) -> "DataUploadSpec.Builder": ...

        @overload
        def csi_snapshot(
            self,
            value_or_callback: Callable[
                [DataUploadSpecCsiSnapshot | None.Builder],
                DataUploadSpecCsiSnapshot | None.Builder | DataUploadSpecCsiSnapshot | None,
            ],
            /,
        ) -> "DataUploadSpec.Builder": ...

        @overload
        def csi_snapshot(
            self, value_or_callback: Never = ...
        ) -> "DataUploadSpecCsiSnapshot | None.BuilderContext": ...

        def csi_snapshot(self, value_or_callback=UNSET, /):
            "If SnapshotType is CSI, CSISnapshot provides the information of the CSI snapshot."
            if self._in_context and value_or_callback is UNSET:
                context = DataUploadSpecCsiSnapshot | None.BuilderContext()
                context._parent_builder = self
                context._field_name = "csi_snapshot"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataUploadSpecCsiSnapshot | None.builder())
                if isinstance(output, DataUploadSpecCsiSnapshot | None.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("csi_snapshot", value)

        def data_mover_config(self, value: dict[str, Any] | None, /) -> Self:
            "DataMoverConfig is for data-mover-specific configuration fields."
            return self._set("data_mover_config", value)

        def datamover(self, value: str | None, /) -> Self:
            'DataMover specifies the data mover to be used by the backup.\nIf DataMover is "" or "velero", the built-in data mover will be used.'
            return self._set("datamover", value)

        def operation_timeout(self, value: str, /) -> Self:
            "OperationTimeout specifies the time used to wait internal operations,\nbefore returning error as timeout."
            return self._set("operation_timeout", value)

        def snapshot_type(self, value: str, /) -> Self:
            "SnapshotType is the type of the snapshot to be backed up."
            return self._set("snapshot_type", value)

        def source_namespace(self, value: str, /) -> Self:
            "SourceNamespace is the original namespace where the volume is backed up from.\nIt is the same namespace for SourcePVC and CSI namespaced objects."
            return self._set("source_namespace", value)

        def source_pvc(self, value: str, /) -> Self:
            "SourcePVC is the name of the PVC which the snapshot is taken for."
            return self._set("source_pvc", value)

    class BuilderContext(BuilderContextBase["DataUploadSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataUploadSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataUploadSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataUploadSpec", Builder]:
        return GenericListBuilder[DataUploadSpec, DataUploadSpec.Builder]()

    backup_storage_location: Annotated[str, Field(alias="backupStorageLocation")]
    "BackupStorageLocation is the name of the backup storage location\nwhere the backup repository is stored."
    cancel: bool | None = None
    "Cancel indicates request to cancel the ongoing DataUpload. It can be set\nwhen the DataUpload is in InProgress phase"
    csi_snapshot: Annotated[DataUploadSpecCsiSnapshot | None, Field(alias="csiSnapshot")] = None
    "If SnapshotType is CSI, CSISnapshot provides the information of the CSI snapshot."
    data_mover_config: Annotated[dict[str, Any] | None, Field(alias="dataMoverConfig")] = None
    "DataMoverConfig is for data-mover-specific configuration fields."
    datamover: str | None = None
    'DataMover specifies the data mover to be used by the backup.\nIf DataMover is "" or "velero", the built-in data mover will be used.'
    operation_timeout: Annotated[str, Field(alias="operationTimeout")]
    "OperationTimeout specifies the time used to wait internal operations,\nbefore returning error as timeout."
    snapshot_type: Annotated[str, Field(alias="snapshotType")]
    "SnapshotType is the type of the snapshot to be backed up."
    source_namespace: Annotated[str, Field(alias="sourceNamespace")]
    "SourceNamespace is the original namespace where the volume is backed up from.\nIt is the same namespace for SourcePVC and CSI namespaced objects."
    source_pvc: Annotated[str, Field(alias="sourcePVC")]
    "SourcePVC is the name of the PVC which the snapshot is taken for."


class DataUploadStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataUploadStatus"]:
            return DataUploadStatus

        def build(self) -> "DataUploadStatus":
            return DataUploadStatus(**self._attrs)

        def completion_timestamp(self, value: AwareDatetime | None, /) -> Self:
            "CompletionTimestamp records the time a backup was completed.\nCompletion time is recorded even on failed backups.\nCompletion time is recorded before uploading the backup object.\nThe server\u0027s time is used for CompletionTimestamps"
            return self._set("completion_timestamp", value)

        def data_mover_result(self, value: dict[str, Any] | None, /) -> Self:
            "DataMoverResult stores data-mover-specific information as a result of the DataUpload."
            return self._set("data_mover_result", value)

        def message(self, value: str | None, /) -> Self:
            "Message is a message about the DataUpload\u0027s status."
            return self._set("message", value)

        def node(self, value: str | None, /) -> Self:
            "Node is name of the node where the DataUpload is processed."
            return self._set("node", value)

        def path(self, value: str | None, /) -> Self:
            "Path is the full path of the snapshot volume being backed up."
            return self._set("path", value)

        def phase(
            self,
            value: (
                Literal[
                    "New",
                    "Accepted",
                    "Prepared",
                    "InProgress",
                    "Canceling",
                    "Canceled",
                    "Completed",
                    "Failed",
                ]
                | None
            ),
            /,
        ) -> Self:
            "Phase is the current state of the DataUpload."
            return self._set("phase", value)

        @overload
        def progress(
            self, value_or_callback: DataUploadStatusProgress | None, /
        ) -> "DataUploadStatus.Builder": ...

        @overload
        def progress(
            self,
            value_or_callback: Callable[
                [DataUploadStatusProgress.Builder],
                DataUploadStatusProgress.Builder | DataUploadStatusProgress,
            ],
            /,
        ) -> "DataUploadStatus.Builder": ...

        @overload
        def progress(
            self, value_or_callback: Never = ...
        ) -> "DataUploadStatusProgress.BuilderContext": ...

        def progress(self, value_or_callback=UNSET, /):
            "Progress holds the total number of bytes of the volume and the current\nnumber of backed up bytes. This can be used to display progress information\nabout the backup operation."
            if self._in_context and value_or_callback is UNSET:
                context = DataUploadStatusProgress.BuilderContext()
                context._parent_builder = self
                context._field_name = "progress"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataUploadStatusProgress.builder())
                if isinstance(output, DataUploadStatusProgress.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("progress", value)

        def snapshot_id(self, value: str | None, /) -> Self:
            "SnapshotID is the identifier for the snapshot in the backup repository."
            return self._set("snapshot_id", value)

        def start_timestamp(self, value: AwareDatetime | None, /) -> Self:
            "StartTimestamp records the time a backup was started.\nSeparate from CreationTimestamp, since that value changes\non restores.\nThe server\u0027s time is used for StartTimestamps"
            return self._set("start_timestamp", value)

    class BuilderContext(BuilderContextBase["DataUploadStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataUploadStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataUploadStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataUploadStatus", Builder]:
        return GenericListBuilder[DataUploadStatus, DataUploadStatus.Builder]()

    completion_timestamp: Annotated[AwareDatetime | None, Field(alias="completionTimestamp")] = None
    "CompletionTimestamp records the time a backup was completed.\nCompletion time is recorded even on failed backups.\nCompletion time is recorded before uploading the backup object.\nThe server\u0027s time is used for CompletionTimestamps"
    data_mover_result: Annotated[dict[str, Any] | None, Field(alias="dataMoverResult")] = None
    "DataMoverResult stores data-mover-specific information as a result of the DataUpload."
    message: str | None = None
    "Message is a message about the DataUpload\u0027s status."
    node: str | None = None
    "Node is name of the node where the DataUpload is processed."
    path: str | None = None
    "Path is the full path of the snapshot volume being backed up."
    phase: (
        Literal[
            "New",
            "Accepted",
            "Prepared",
            "InProgress",
            "Canceling",
            "Canceled",
            "Completed",
            "Failed",
        ]
        | None
    ) = None
    "Phase is the current state of the DataUpload."
    progress: DataUploadStatusProgress | None = None
    "Progress holds the total number of bytes of the volume and the current\nnumber of backed up bytes. This can be used to display progress information\nabout the backup operation."
    snapshot_id: Annotated[str | None, Field(alias="snapshotID")] = None
    "SnapshotID is the identifier for the snapshot in the backup repository."
    start_timestamp: Annotated[AwareDatetime | None, Field(alias="startTimestamp")] = None
    "StartTimestamp records the time a backup was started.\nSeparate from CreationTimestamp, since that value changes\non restores.\nThe server\u0027s time is used for StartTimestamps"


class DataDownload(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "datadownloads",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataDownload"]:
            return DataDownload

        def build(self) -> "DataDownload":
            return DataDownload(**self._attrs)

        def api_version(self, value: Literal["velero.io/v2alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["DataDownload"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "DataDownload.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "DataDownload.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: DataDownloadSpec | None, /) -> "DataDownload.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [DataDownloadSpec.Builder], DataDownloadSpec.Builder | DataDownloadSpec
            ],
            /,
        ) -> "DataDownload.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "DataDownloadSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = DataDownloadSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataDownloadSpec.builder())
                if isinstance(output, DataDownloadSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: DataDownloadStatus | None, /
        ) -> "DataDownload.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [DataDownloadStatus.Builder],
                DataDownloadStatus.Builder | DataDownloadStatus,
            ],
            /,
        ) -> "DataDownload.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "DataDownloadStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = DataDownloadStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataDownloadStatus.builder())
                if isinstance(output, DataDownloadStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["DataDownload.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataDownload.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataDownload."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataDownload", Builder]:
        return GenericListBuilder[DataDownload, DataDownload.Builder]()

    api_version: Annotated[Literal["velero.io/v2alpha1"], Field(alias="apiVersion")] = (
        "velero.io/v2alpha1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["DataDownload"] = "DataDownload"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: DataDownloadSpec | None = None
    status: DataDownloadStatus | None = None


class DataUpload(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "datauploads",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["DataUpload"]:
            return DataUpload

        def build(self) -> "DataUpload":
            return DataUpload(**self._attrs)

        def api_version(self, value: Literal["velero.io/v2alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["DataUpload"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "DataUpload.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "DataUpload.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: DataUploadSpec | None, /) -> "DataUpload.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [DataUploadSpec.Builder], DataUploadSpec.Builder | DataUploadSpec
            ],
            /,
        ) -> "DataUpload.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "DataUploadSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = DataUploadSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataUploadSpec.builder())
                if isinstance(output, DataUploadSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: DataUploadStatus | None, /) -> "DataUpload.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [DataUploadStatus.Builder], DataUploadStatus.Builder | DataUploadStatus
            ],
            /,
        ) -> "DataUpload.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "DataUploadStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = DataUploadStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(DataUploadStatus.builder())
                if isinstance(output, DataUploadStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["DataUpload.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = DataUpload.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for DataUpload."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["DataUpload", Builder]:
        return GenericListBuilder[DataUpload, DataUpload.Builder]()

    api_version: Annotated[Literal["velero.io/v2alpha1"], Field(alias="apiVersion")] = (
        "velero.io/v2alpha1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["DataUpload"] = "DataUpload"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: DataUploadSpec | None = None
    status: DataUploadStatus | None = None
